# Generated by Django 4.1.7 on 2023-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_regi_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='regi',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
    ]
